[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "linkedlist"
version = "0.1"
requires-python = ">= 3.12"
description = "linked list implementations"

