[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tkml"
version = "0.1"
requires-python = ">= 3.12"
description = "[ html, css, js] -> [ tkml, toml, py ]"

