[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "k-lab"
version = "0.0.1"
requires-python = ">= 3.12"
description = "tools for measuring code performance"

