[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "klab"
version = "0.0.2"
requires-python = ">= 3.12"
description = "tools for measuring code performance"

